additionalRepositories:
  # - url: https://github.com/nextflow-io/nextflow
  - url: https://github.com/mahesh-panchal/nf-core_metamap-management-poc

tasks:
  - name: Install Nextflow
    command: curl -s https://get.nextflow.io | bash